name: CI/CD to EC2

on:
  push:
    branches: ["master"] # master 브랜치에 push될 때 동작

jobs:
  build-and-deploy:
    runs-on: self-hosted # 실행 환경

    steps:
      # 1. 저장소 코드 가져오기
      - uses: actions/checkout@v3

      # 2. Docker Hub 로그인 (secrets 필요)
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 3. Docker 이미지 빌드 & 푸시
      - run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/front:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/front:latest

      # 4. EC2 안에서 바로 실행
      - run: |
          sudo docker stop front || true
          sudo docker rm front || true
          sudo docker run -d --name front \
            --env-file /home/ubuntu/app/.env \
            -p 3001:3000 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/front:latest
